fixed bugs found while creating new officers
parkr-unb/parkr pull request #53
Opened 2022-03-23 18:59 UTC by justend29

made manage officers pretty, too

2022-03-23 20:14 UTC, StephenCole19 commented on lib/main.dart
> +                "Jesus Loves You");
yeet

2022-03-23 20:15 UTC, StephenCole19 commented on lib/widgets/loginform.dart
> +                      print("LITERALLY FUCK YOU");
yeet

2022-03-23 20:16 UTC, StephenCole19 requested changes
Please fix *interesting prints*

2022-03-24 02:04 UTC, justend29 commented on lib/main.dart
> +                "Jesus Loves You");
this has to actually stay

2022-03-24 02:04 UTC, justend29 commented on lib/widgets/loginform.dart
> +                      print("LITERALLY FUCK YOU");
thank you for catching this

2022-03-24 16:48 UTC, StephenCole19 approved these changes

2022-03-24 16:49 UTC, merged