Feat google geofence
parkr-unb/parkr pull request #62
Opened 2022-03-26 22:07 UTC by reidhurlburt

Add all the geofence functionality.

I've noticed that a notification saying the app is not responding pops up every now and then. If that starts happening to everyone and not just my 8GB DDR3 laptop, then it's probably in here.

2022-03-27 01:43 UTC, reidhurlburt commented
> Add all the geofence functionality.
> 
> I've noticed that a notification saying the app is not responding pops up every now and then. If that starts happening to everyone and not just my 8GB DDR3 laptop, then it's probably in here.

Looks like it was just the state of my emulator, disregard

2022-03-28 04:24 UTC, ChrisRuff requested changes

2022-03-28 04:24 UTC, ChrisRuff commented on lib/gateway.dart
> +      Organization? organization = await getOrganization('unb');
We dont hardcode UNB, use CurrentUser().getOrg()

2022-03-28 04:24 UTC, ChrisRuff commented on lib/gateway.dart
> +      Organization? organization = await getOrganization('unb');
See comment above

2022-03-28 04:24 UTC, ChrisRuff commented on lib/gateway.dart
> +      Organization? organization = await getOrganization('unb');
See comment above x2

2022-03-28 04:24 UTC, ChrisRuff commented on lib/views/homepage.dart
> +                              Gateway().inParkingLot(curLoc, 'unb'),
We dont need to hardcode org, use CurrentUser().getOrg()

2022-03-28 04:24 UTC, ChrisRuff commented on lib/gateway.dart
> +          }
The dart null dance above is ridiculous, but I approve

2022-03-28 04:24 UTC, ChrisRuff commented on lib/main.dart
> +      print("Service is f'd");
Lets clean up some prints

2022-03-28 04:24 UTC, ChrisRuff commented on lib/main.dart
> +      print("Permission is f'd");
Clean up prints

2022-03-29 16:40 UTC, ChrisRuff approved these changes

2022-03-29 16:40 UTC, merged